---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
  - aggregator

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
  - aggregator

- name: Install td-agent.
  package:
    name: td-agent
    state: "{{ fluentd_package_state }}"
  tags:
  - aggregator

- name: "Add user to {{ fluentd_groups | join(',') }} group"
  user:
    name: td-agent
    group: td-agent
    state: present
    groups: '{{ fluentd_extra_groups | join(",") }}'
    append: true
  when: fluentd_extra_groups is defined
  tags:
  - aggregator

- name: Configure Fluentd.
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent 
    group: td-agent
    mode: 0640
  notify: restart fluentd
  tags:
  - aggregator

- name: Ensure Fluentd plugins are installed.
  gem:
    name: "{{ item.name | default(item) }}"
    executable: /usr/sbin/td-agent-gem 
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: false
  with_items: "{{ fluentd_plugins }}"
  tags:
  - aggregator

- name: Start Fluentd.
  systemd:
    name: "{{ fluentd_service_name }}"
    state: "{{ fluentd_service_state }}"
    enabled: "{{ fluentd_service_enabled }}"
  tags:
  - aggregator
