---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install td-agent.
  package:
    name: td-agent
    state: "{{ fluentd_package_state }}"

- name: "Add user to {{ fluentd_groups | join(',') }} group"
  user:
    name: td-agent
    group: td-agent
    state: present
    groups: '{{ fluentd_extra_groups | join(",") }}'
    append: true
  when: fluentd_groups is defined

- name: Configure Fluentd.
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fluentd

- name: Ensure Fluentd plugins are installed.
  gem:
    name: "{{ item.name | default(item) }}"
    executable: /usr/sbin/td-agent-gem 
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: false
  with_items: "{{ fluentd_plugins }}"

- name: retrieve initial ExecStart
  shell: 'grep -i "ExecStart=.*/.*" /lib/systemd/system/td-agent.service | sed -r "s/^([^\/])*(\/.*)/\2/"'
  register: initial_cmd
  tags:
  - never
  - aggregator

- name: Ensure unit directory is present
  file:
    path: /etc/systemd/system/td-agent.service.d
    state: directory
    mode: '0755'
  tags:
  - never
  - aggregator

- name: Add unit override.conf file
  template:
    src: templates/override.conf.j2
    dest: /etc/systemd/system/td-agent.service.d/override.conf
  tags:
  - never
  - aggregator

- name: Start Fluentd.
  systemd:
    daemon_reload: yes
    name: "{{ fluentd_service_name }}"
    state: "{{ fluentd_service_state }}"
    enabled: "{{ fluentd_service_enabled }}"
